import type { PracticeOptionId, PublicPracticeQuestion } from "@/lib/practice-bank";

export type ExpandedPracticeQuestion = PublicPracticeQuestion & {
  correctOptionId: PracticeOptionId;
  explanation: string;
  trap: string;
  optionFeedback: Record<PracticeOptionId, string>;
};

type QuestionInput = Omit<ExpandedPracticeQuestion, "options" | "optionFeedback"> & {
  options: [string, string, string, string];
};

const optionIds: PracticeOptionId[] = ["A", "B", "C", "D"];

function makeQuestion(input: QuestionInput): ExpandedPracticeQuestion {
  const options = optionIds.map((id, index) => ({ id, text: input.options[index] }));
  const optionFeedback = Object.fromEntries(
    options.map((option) => [
      option.id,
      option.id === input.correctOptionId
        ? input.explanation
        : `« ${option.text} » ne correspond pas à la grammaire ou au sens attendu dans ce contexte.`
    ])
  ) as Record<PracticeOptionId, string>;
  return { ...input, options, optionFeedback };
}

export const extraPracticeQuestions: ExpandedPracticeQuestion[] = [
  makeQuestion({
    id: "practice-tense-04",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "Present simple after time clause",
    difficulty: 3,
    targetTimeMs: 30000,
    prompt: "The finance director will approve the payment as soon as she ______ the final invoice.",
    options: ["receives", "will receive", "received", "is received"],
    correctOptionId: "A",
    explanation: "Après as soon as pour parler du futur, la proposition temporelle reste au présent simple : as soon as she receives.",
    trap: "Mettre will dans les deux propositions parce que l’action est future."
  }),
  makeQuestion({
    id: "practice-tense-05",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "Past perfect",
    difficulty: 3,
    targetTimeMs: 32000,
    prompt: "The warehouse was empty because the supplier ______ the shipment to another site.",
    options: ["redirects", "had redirected", "has redirected", "will redirect"],
    correctOptionId: "B",
    explanation: "La redirection a eu lieu avant le constat passé « was empty » : on emploie le past perfect.",
    trap: "Choisir le past simple sans marquer l’antériorité entre deux actions passées."
  }),
  makeQuestion({
    id: "practice-tense-06",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "Present continuous arrangement",
    difficulty: 2,
    targetTimeMs: 26000,
    prompt: "Ms. Patel ______ the regional managers at 10 a.m. tomorrow.",
    options: ["meets", "met", "is meeting", "has met"],
    correctOptionId: "C",
    explanation: "Le present continuous peut exprimer un rendez-vous futur déjà organisé.",
    trap: "Choisir le présent simple uniquement parce qu’une heure précise est donnée."
  }),
  makeQuestion({
    id: "practice-tense-07",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "Present perfect continuous",
    difficulty: 4,
    targetTimeMs: 35000,
    prompt: "The technicians ______ the network problem since early this morning.",
    options: ["investigate", "investigated", "have been investigating", "had investigated"],
    correctOptionId: "C",
    explanation: "Since indique un point de départ passé et l’action continue au présent : have been investigating.",
    trap: "Confondre une action toujours en cours avec une action entièrement terminée."
  }),
  makeQuestion({
    id: "practice-tense-08",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "Past continuous",
    difficulty: 2,
    targetTimeMs: 28000,
    prompt: "While the receptionist ______ a client, the fire alarm went off.",
    options: ["assisted", "was assisting", "has assisted", "will assist"],
    correctOptionId: "B",
    explanation: "Une action longue en cours dans le passé est interrompue par un événement court : was assisting.",
    trap: "Mettre les deux actions au past simple et perdre l’idée d’action en cours."
  }),
  makeQuestion({
    id: "practice-tense-09",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "Future perfect",
    difficulty: 4,
    targetTimeMs: 34000,
    prompt: "By next Friday, all department heads ______ their budget proposals.",
    options: ["submit", "will have submitted", "had submitted", "are submitting yesterday"],
    correctOptionId: "B",
    explanation: "By next Friday fixe une échéance future avant laquelle l’action sera achevée : will have submitted.",
    trap: "Employer le futur simple alors que la phrase insiste sur le résultat déjà acquis."
  }),
  makeQuestion({
    id: "practice-tense-10",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "First conditional",
    difficulty: 3,
    targetTimeMs: 30000,
    prompt: "If the client ______ the revised terms, we will issue a new contract.",
    options: ["accepts", "will accept", "accepted", "has accepting"],
    correctOptionId: "A",
    explanation: "Dans le first conditional, la proposition introduite par if est au présent simple, puis la principale utilise will.",
    trap: "Employer will immédiatement après if."
  }),
  makeQuestion({
    id: "practice-tense-11",
    part: 5,
    skillId: "grammar_tenses",
    skillLabel: "Temps verbaux",
    subskill: "Present perfect result",
    difficulty: 2,
    targetTimeMs: 27000,
    prompt: "The maintenance team ______ the elevator, so it is available again.",
    options: ["repairs", "repaired last year", "has repaired", "had repairing"],
    correctOptionId: "C",
    explanation: "Le résultat est visible maintenant (« available again »), donc le present perfect convient.",
    trap: "Choisir le past simple sans repère passé terminé."
  }),
  makeQuestion({
    id: "practice-prep-04",
    part: 5,
    skillId: "grammar_prepositions",
    skillLabel: "Prépositions",
    subskill: "Cause",
    difficulty: 2,
    targetTimeMs: 25000,
    prompt: "The outdoor event was postponed ______ heavy rain.",
    options: ["due to", "among", "throughout", "beside"],
    correctOptionId: "A",
    explanation: "Due to introduit la cause d’un événement.",
    trap: "Choisir une préposition connue sans vérifier la relation logique de cause."
  }),
  makeQuestion({
    id: "practice-prep-05",
    part: 5,
    skillId: "grammar_prepositions",
    skillLabel: "Prépositions",
    subskill: "Conformité",
    difficulty: 3,
    targetTimeMs: 29000,
    prompt: "All contractors must comply ______ the site’s safety regulations.",
    options: ["to", "with", "for", "at"],
    correctOptionId: "B",
    explanation: "La collocation correcte est comply with + règle ou exigence.",
    trap: "Traduire littéralement « se conformer à » par comply to."
  }),
  makeQuestion({
    id: "practice-prep-06",
    part: 5,
    skillId: "grammar_prepositions",
    skillLabel: "Prépositions",
    subskill: "Responsabilité",
    difficulty: 3,
    targetTimeMs: 29000,
    prompt: "Mr. Lee is in charge ______ coordinating the product launch.",
    options: ["of", "for", "with", "from"],
    correctOptionId: "A",
    explanation: "L’expression fixe est be in charge of + nom ou verbe en -ing.",
    trap: "Confondre in charge of avec responsible for."
  }),
  makeQuestion({
    id: "practice-prep-07",
    part: 5,
    skillId: "grammar_prepositions",
    skillLabel: "Prépositions",
    subskill: "Avance",
    difficulty: 3,
    targetTimeMs: 30000,
    prompt: "The renovation was completed two weeks ______ schedule.",
    options: ["ahead of", "between", "under", "since"],
    correctOptionId: "A",
    explanation: "Ahead of schedule signifie en avance sur le calendrier prévu.",
    trap: "Choisir before schedule, qui est moins idiomatique dans cette expression professionnelle."
  }),
  makeQuestion({
    id: "practice-prep-08",
    part: 6,
    skillId: "grammar_prepositions",
    skillLabel: "Prépositions",
    subskill: "Période",
    difficulty: 2,
    targetTimeMs: 32000,
    context: "MEMO — The customer-service desk will remain open ______ the lunch period this week to handle increased demand.",
    prompt: "Which word best completes the memo?",
    options: ["during", "until", "among", "toward"],
    correctOptionId: "A",
    explanation: "During signifie pendant une période définie.",
    trap: "Confondre during avec until, qui marque une limite dans le temps."
  }),
  makeQuestion({
    id: "practice-structure-04",
    part: 5,
    skillId: "grammar_structure",
    skillLabel: "Structure grammaticale",
    subskill: "Subject-verb agreement",
    difficulty: 3,
    targetTimeMs: 30000,
    prompt: "Neither the director nor the assistants ______ available for comment.",
    options: ["was", "is", "are", "has"],
    correctOptionId: "C",
    explanation: "Avec neither...nor, le verbe s’accorde généralement avec le sujet le plus proche : assistants → are.",
    trap: "Accorder automatiquement avec le premier nom singulier."
  }),
  makeQuestion({
    id: "practice-structure-05",
    part: 5,
    skillId: "grammar_structure",
    skillLabel: "Structure grammaticale",
    subskill: "Adverbe",
    difficulty: 2,
    targetTimeMs: 27000,
    prompt: "The new software allows employees to process requests more ______.",
    options: ["efficient", "efficiency", "efficiently", "efficiencies"],
    correctOptionId: "C",
    explanation: "Le mot modifie le verbe process : il faut l’adverbe efficiently.",
    trap: "Choisir l’adjectif efficient parce qu’il est plus familier."
  }),
  makeQuestion({
    id: "practice-structure-06",
    part: 5,
    skillId: "grammar_structure",
    skillLabel: "Structure grammaticale",
    subskill: "Passive infinitive",
    difficulty: 4,
    targetTimeMs: 34000,
    prompt: "The documents are expected ______ before the inspection begins.",
    options: ["to submit", "to be submitted", "submitting", "submitted them"],
    correctOptionId: "B",
    explanation: "Les documents reçoivent l’action : expected to be submitted.",
    trap: "Oublier la voix passive après be expected."
  }),
  makeQuestion({
    id: "practice-structure-07",
    part: 5,
    skillId: "grammar_structure",
    skillLabel: "Structure grammaticale",
    subskill: "Gerund after verb",
    difficulty: 3,
    targetTimeMs: 30000,
    prompt: "The company avoided ______ additional fees by renewing the license early.",
    options: ["pay", "to pay", "paying", "paid"],
    correctOptionId: "C",
    explanation: "Avoid est suivi d’un nom ou d’un gérondif : avoid paying.",
    trap: "Employer l’infinitif après tous les verbes sans connaître leur construction."
  }),
  makeQuestion({
    id: "practice-structure-08",
    part: 6,
    skillId: "grammar_structure",
    skillLabel: "Structure grammaticale",
    subskill: "Participe passé adjectival",
    difficulty: 3,
    targetTimeMs: 33000,
    context: "The conference room has been fully ______ with video equipment for hybrid meetings.",
    prompt: "Which form best completes the sentence?",
    options: ["equip", "equipping", "equipped", "equipment"],
    correctOptionId: "C",
    explanation: "Après has been, il faut le participe passé equipped pour former la voix passive.",
    trap: "Choisir equipment parce que le contexte parle de matériel."
  }),
  makeQuestion({
    id: "practice-vocab-04",
    part: 5,
    skillId: "business_vocabulary",
    skillLabel: "Vocabulaire professionnel",
    subskill: "Facturation",
    difficulty: 2,
    targetTimeMs: 27000,
    prompt: "Please include the purchase-order number on every ______ sent to the accounting department.",
    options: ["invoice", "interview", "inventory", "invitation"],
    correctOptionId: "A",
    explanation: "An invoice est une facture envoyée au service comptable.",
    trap: "Se laisser attirer par des mots proches visuellement."
  }),
  makeQuestion({
    id: "practice-vocab-05",
    part: 5,
    skillId: "business_vocabulary",
    skillLabel: "Vocabulaire professionnel",
    subskill: "Recrutement",
    difficulty: 2,
    targetTimeMs: 27000,
    prompt: "The company posted a new job ______ on its careers page.",
    options: ["vacancy", "vacation", "vaccine", "variety"],
    correctOptionId: "A",
    explanation: "A job vacancy désigne un poste vacant à pourvoir.",
    trap: "Confondre vacancy et vacation."
  }),
  makeQuestion({
    id: "practice-vocab-06",
    part: 5,
    skillId: "business_vocabulary",
    skillLabel: "Vocabulaire professionnel",
    subskill: "Service après-vente",
    difficulty: 3,
    targetTimeMs: 30000,
    prompt: "Repairs are free while the appliance is still under ______.",
    options: ["warranty", "warehouse", "withdrawal", "workforce"],
    correctOptionId: "A",
    explanation: "Under warranty signifie encore couvert par la garantie.",
    trap: "Choisir warehouse à cause du contexte matériel."
  }),
  makeQuestion({
    id: "practice-vocab-07",
    part: 5,
    skillId: "business_vocabulary",
    skillLabel: "Vocabulaire professionnel",
    subskill: "Réseau commercial",
    difficulty: 2,
    targetTimeMs: 28000,
    prompt: "The bank plans to open a new ______ near the airport.",
    options: ["branch", "brand", "brief", "budget"],
    correctOptionId: "A",
    explanation: "A branch est une agence ou succursale d’une entreprise.",
    trap: "Confondre branch et brand."
  }),
  makeQuestion({
    id: "practice-vocab-08",
    part: 5,
    skillId: "business_vocabulary",
    skillLabel: "Vocabulaire professionnel",
    subskill: "Paiement",
    difficulty: 3,
    targetTimeMs: 30000,
    prompt: "A reminder was sent because the customer’s payment was ______.",
    options: ["overdue", "overseas", "overtime", "overlooked"],
    correctOptionId: "A",
    explanation: "Overdue signifie en retard par rapport à l’échéance.",
    trap: "Choisir un mot commençant par over- sans vérifier le sens."
  }),
  makeQuestion({
    id: "practice-detail-04",
    part: 7,
    skillId: "reading_detail",
    skillLabel: "Compréhension des détails",
    subskill: "Date",
    difficulty: 2,
    targetTimeMs: 47000,
    context: "NOTICE — The staff parking area will be resurfaced on Saturday, May 18. Employees may use the visitor lot that day.",
    prompt: "When will the staff parking area be unavailable?",
    options: ["On Friday", "On May 18", "Every Saturday", "After May 18"],
    correctOptionId: "B",
    explanation: "Le texte indique précisément Saturday, May 18.",
    trap: "Retenir seulement le jour de la semaine et ignorer la date."
  }),
  makeQuestion({
    id: "practice-detail-05",
    part: 7,
    skillId: "reading_detail",
    skillLabel: "Compréhension des détails",
    subskill: "Document requis",
    difficulty: 3,
    targetTimeMs: 50000,
    context: "EMAIL — To complete your registration, upload a copy of your identification and the signed consent form. Payment has already been received.",
    prompt: "What must the recipient still provide?",
    options: ["A payment", "A photograph only", "Two documents", "A new application"],
    correctOptionId: "C",
    explanation: "Il reste à fournir une pièce d’identité et le formulaire signé, soit deux documents.",
    trap: "Choisir payment alors que le message dit qu’il a déjà été reçu."
  }),
  makeQuestion({
    id: "practice-detail-06",
    part: 7,
    skillId: "reading_detail",
    skillLabel: "Compréhension des détails",
    subskill: "Changement d’horaire",
    difficulty: 2,
    targetTimeMs: 47000,
    context: "MEMO — The monthly sales meeting will begin at 2:30 p.m. instead of 3:00 p.m. The location remains Meeting Room 4.",
    prompt: "What has changed?",
    options: ["The room", "The date", "The starting time", "The attendees"],
    correctOptionId: "C",
    explanation: "Seule l’heure de début passe de 15 h à 14 h 30.",
    trap: "Inventer un changement de lieu alors que le texte précise qu’il reste identique."
  }),
  makeQuestion({
    id: "practice-detail-07",
    part: 7,
    skillId: "reading_detail",
    skillLabel: "Compréhension des détails",
    subskill: "Avantage client",
    difficulty: 3,
    targetTimeMs: 52000,
    context: "ADVERTISEMENT — Members receive free standard delivery on orders over €40 and can return unused items within 30 days.",
    prompt: "Which benefit is mentioned?",
    options: ["Same-day delivery", "Free delivery under a condition", "Unlimited returns", "A permanent discount"],
    correctOptionId: "B",
    explanation: "La livraison standard est gratuite pour les commandes supérieures à 40 €.",
    trap: "Oublier la condition liée au montant de la commande."
  }),
  makeQuestion({
    id: "practice-detail-08",
    part: 7,
    skillId: "reading_detail",
    skillLabel: "Compréhension des détails",
    subskill: "Responsable",
    difficulty: 3,
    targetTimeMs: 50000,
    context: "EMAIL — Please send all travel receipts to Marco in Finance. He will review them before forwarding approved claims to Payroll.",
    prompt: "Who reviews the receipts first?",
    options: ["Payroll", "Marco", "The traveler", "Human Resources"],
    correctOptionId: "B",
    explanation: "Marco examine les justificatifs avant de transmettre les demandes approuvées.",
    trap: "Choisir Payroll parce que ce service intervient plus tard."
  }),
  makeQuestion({
    id: "practice-inference-04",
    part: 7,
    skillId: "reading_inference",
    skillLabel: "Inférences",
    subskill: "But du message",
    difficulty: 3,
    targetTimeMs: 54000,
    context: "MESSAGE — The projector in Room 12 is displaying a warning light again. Could someone check it before the client presentation at 1 p.m.?",
    prompt: "Why was this message most likely sent?",
    options: ["To reserve a room", "To request technical help", "To cancel a presentation", "To order a new projector"],
    correctOptionId: "B",
    explanation: "Le message signale un problème et demande que quelqu’un vérifie l’appareil.",
    trap: "Choisir une solution extrême qui n’est pas demandée."
  }),
  makeQuestion({
    id: "practice-inference-05",
    part: 7,
    skillId: "reading_inference",
    skillLabel: "Inférences",
    subskill: "Étape suivante",
    difficulty: 4,
    targetTimeMs: 56000,
    context: "EMAIL — Your draft has been approved with one minor change: replace the old contact number on the final page. Once that is done, the document can be published.",
    prompt: "What will the recipient probably do next?",
    options: ["Rewrite the entire document", "Update one detail", "Contact a printer", "Request another approval meeting"],
    correctOptionId: "B",
    explanation: "La seule modification demandée est le remplacement du numéro de contact.",
    trap: "Surestimer l’ampleur du travail restant."
  }),
  makeQuestion({
    id: "practice-inference-06",
    part: 7,
    skillId: "reading_inference",
    skillLabel: "Inférences",
    subskill: "Situation probable",
    difficulty: 4,
    targetTimeMs: 57000,
    context: "REVIEW — The apartment was clean and close to the station. However, the Wi-Fi stopped working every evening, which made video calls difficult.",
    prompt: "Who would be most concerned by the problem mentioned?",
    options: ["A remote worker", "A train driver", "A cleaner", "A tourist without devices"],
    correctOptionId: "A",
    explanation: "Une personne travaillant à distance dépend des appels vidéo et serait directement gênée.",
    trap: "Choisir une personne liée à un détail positif plutôt qu’au problème."
  }),
  makeQuestion({
    id: "practice-inference-07",
    part: 7,
    skillId: "reading_inference",
    skillLabel: "Inférences",
    subskill: "Implication",
    difficulty: 4,
    targetTimeMs: 58000,
    context: "NOTICE — Due to limited seating, employees who have not registered by Wednesday may attend the workshop online instead.",
    prompt: "What is implied about the in-person workshop?",
    options: ["It has been cancelled", "It may become full", "It is only for managers", "It has no online option"],
    correctOptionId: "B",
    explanation: "La limitation des places et l’alternative en ligne indiquent que la salle peut être complète.",
    trap: "Transformer une contrainte de capacité en annulation complète."
  })
];